// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBASQrPh3dBBONbOJff2t8FK1rRBsEUWJU',
    appId: '1:1032855565086:web:e57b625011a9162af84f0f',
    messagingSenderId: '1032855565086',
    projectId: 'pmtc-project-96c44',
    authDomain: 'pmtc-project-96c44.firebaseapp.com',
    storageBucket: 'pmtc-project-96c44.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTpe6O5roSgCKER1GnAXptp52GcHfhIuY',
    appId: '1:1032855565086:android:0ef9816bef77e371f84f0f',
    messagingSenderId: '1032855565086',
    projectId: 'pmtc-project-96c44',
    storageBucket: 'pmtc-project-96c44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfn4WgwjModmEQkgYnDG9MM0EYTEGPFDs',
    appId: '1:1032855565086:ios:65f585a2b8d63f12f84f0f',
    messagingSenderId: '1032855565086',
    projectId: 'pmtc-project-96c44',
    storageBucket: 'pmtc-project-96c44.appspot.com',
    iosClientId: '1032855565086-8br0m4ref96f5oqcsldf7kj9cnk9hnb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.pmtcProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfn4WgwjModmEQkgYnDG9MM0EYTEGPFDs',
    appId: '1:1032855565086:ios:65f585a2b8d63f12f84f0f',
    messagingSenderId: '1032855565086',
    projectId: 'pmtc-project-96c44',
    storageBucket: 'pmtc-project-96c44.appspot.com',
    iosClientId: '1032855565086-8br0m4ref96f5oqcsldf7kj9cnk9hnb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.pmtcProject',
  );
}
